language: go

go:
  - 1.4
  - tip
install:
  - cd $HOME/gopath/src/github.com/NeowayLabs/neosearch
  - go get -d -v ./...
  - go build -v ./...
script:
  - go get golang.org/x/tools/cmd/vet
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get -u github.com/golang/lint/golint
  - go get github.com/tools/godep
  - go get golang.org/x/tools/cover
  - hack/check.sh
#  - goveralls -coverprofile=coverage.txt -service=travis-ci
before_install:
  sudo pip install codecov
after_success:
  codecov
notifications:
  email:
    - tiago.natel@neoway.com.br
    - tiagokatcipis@gmail.com
    - paulo.pizarro@gmail.com
  webhooks:
    urls:
      - "https://webhooks.gitter.im/e/5c49f66645e9c101199e"
    on_success: change
    on_failure: always
    on_start: false
