language: go

go:
  - 1.3
  - tip
install: go get -d -v ./... && go build -v ./...
script:
  - go get golang.org/x/tools/cmd/vet
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
  - go test -v -bench . -cpu 1,2,4,8 ./... 

notifications:
  email:
    - tiago.natel@neoway.com.br
