language: go

go:
  - 1.3
  - tip
install: go get -tags leveldb -d -v ./... && go build -tags leveldb -v
script:
  - cd /tmp && git clone https://github.com/google/leveldb.git && cd /tmp/leveldb && make
  - go get golang.org/x/tools/cmd/vet
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
  - go test -tags leveldb -v ./... 

notifications:
  email:
    - tiago.natel@neoway.com.br
