# neosearch configuration file

# Root directory where all of the indices will be written.
dataDir: /data

# Enables debug in every neosearch module
debug: false

# enable/disable cache support
enableCache: true

# CacheSize is the length of LRU cache used by the storage engine
# Default is 1GB (1 << 30)
cacheSize: 1073741824

# maxIndicesOpen is the max number of indices maintained open by neosearch
# for cached searchs
maxIndicesOpen: 10