#!/bin/bash

set -e

DEST=$1
BINARY_NAME="neosearch-cli-$VERSION"

echo "restoring $GOPATH"
godep restore

go build \
   -v \
   -tags "$STORAGE_ENGINE" \
   -o "$DEST/$BINARY_NAME" \
   ./cmd/neosearch-cli

echo "Created binary: $DEST/$BINARY_FULLNAME"
ln -sf "$BINARY_NAME" "$DEST/neosearch-cli"

