#!/bin/bash

set -e

DEST=$1
BINARY_NAME="nsimport-$VERSION"

go build \
   -v \
   -tags "$STORAGE_ENGINE" \
   -o "$DEST/$BINARY_NAME" \
   ./cmd/import

echo "Created binary: $DEST/$BINARY_FULLNAME"
ln -sf "$BINARY_NAME" "$DEST/nsimport"

