#!/bin/bash

set -e

DEST=$1
BINARY_NAME="neosearch-$VERSION"

echo "Building with -tags $STORAGE_ENGINE"
go get -tags "$STORAGE_ENGINE" ./service/neosearch/...
go build \
   -tags "$STORAGE_ENGINE" \
   -o "$DEST/$BINARY_NAME" \
   ./service/neosearch

echo "Created binary: $DEST/$BINARY_FULLNAME"
ln -sf "$BINARY_NAME" "$DEST/neosearch"

