#!/bin/bash

set -e

DEST=$1
BINARY_NAME="neosearch-$VERSION"

go build \
   -tags "$STORAGE_ENGINE" \
   -o "$DEST/$BINARY_NAME" \
   ./neosearch

echo "Created binary: $DEST/$BINARY_FULLNAME"
ln -sf "$BINARY_NAME" "$DEST/neosearch"

